apiversion: eks.io/v1alpha5
kind: ClusterConfig
metadata: 
  name: eks-test-cluster
  region: eu-west-1

vpc:
  subnets:
    private:
      eu-west-1a: { id: subnet-0123abc456def }
    public:
      eu-west1-b: { id: subnet-0786ghi987jkl }

nodeGroups:
  - name: testClusterNodes
    instanceType: t2.micro
    desiredCapacity: 2
