apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backendconfig-name
spec:
  healthCheck:
    checkIntervalSec: 60
    timeoutSec: 40
    type: HTTP
    requestPath: /
    port: 80
