apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: app-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 60
    timeoutSec: 40
    type: HTTP
    requestPath: /login
    port: 80