apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-name
  namespace: namespace-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role
subjects:
  - kind: ServiceAccount
    name: svc-account-name
    namespace: namespace-name
