apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cj-example
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cronjob
        spec:
          serviceAccountName: svc-account-name
          containers:
            - env:
                - name: APP_DEBUG
                  value: "true"
                - name: APP_ENV
                  value: local
                - name: APP_KEY
                  value: ''
                - name: DB_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      key: MYSQL_DB
                      name: env
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: MYSQL_USERNAME
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: MYSQL_PASSWORD
                - name: DB_HOST
                  value: db
                - name: DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      key: MYSQL_PORT
                      name: env
              name: container-name
              image: gcr.io/$PROJECT_ID/img-name:tag
              args:
                - php
                - artisan 
                - queue:queue-name 
                - --stop-when-empty 
                - --tries=1 
                - --queue=queue-name
                - --timeout=12000
          restartPolicy: Never
