apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cj
  namespace: default
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cj-app
        spec:
          containers:
          - env:
            - name: DB_HOST
              value: db
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DB
                  name: env
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            name: container-name
            image: gcr.io/$PROJECT_ID/img-name:latest
            args:
              - python 
              - weather.py
              - 4475,9999
          restartPolicy: Never
